name: Ruby

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup docker
      shell: bash
      run: |
        # イメージのビルド
        docker-compose build
        # データベースの作成
        docker-compose run api rails ridgepole:apply
      env:
        RAILS_ENV: test

    - name: Run RSpec
      shell: bash
      run: |
        docker-compose run api bundle exec rspec
      env:
        RAILS_ENV: test
